version: '3.8'

services:
  furapp-db:
    image: mariadb:10.11
    container_name: furapp-db
    environment:
      MYSQL_ROOT_PASSWORD: qhG171U4
      MYSQL_DATABASE: furapp
      MYSQL_TCP_PORT: 3306
    ports:
      - "18046:3306" 
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -P 3306 --silent"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - furapp-network

volumes:
  mariadb_data:

networks:
  furapp-network:
    driver: bridge